package com.valent.pricewell

public enum RoleId {
	USER("USER"),
	ADMINISTRATOR("SYSTEM ADMINISTRATOR"),
    PORTFOLIO_MANAGER("PORTFOLIO MANAGER"),
	PRODUCT_MANAGER("PRODUCT MANAGER"),
	SERVICE_DESIGNER("SERVICE DESIGNER"),
	SALES_PRESIDENT("SALES PRESIDENT"),
	SALES_MANAGER("SALES MANAGER"),
	SALES_PERSON("SALES PERSON"),
	DELIVERY_ROLE_MANAGER("DELIVERY ROLE MANAGER"),
	GENERAL_MANAGER("GENERAL MANAGER"),
	OTHERS("OTHERS")
	
	String code
	
	RoleId(String code)
	{
		this.code = code 
	} 
	
	static list() {
		[USER,
		ADMINISTRATOR,
		PORTFOLIO_MANAGER,
		PRODUCT_MANAGER,
		SERVICE_DESIGNER,
		SALES_PRESIDENT,
		SALES_MANAGER,
		SALES_PERSON,
		DELIVERY_ROLE_MANAGER,
		GENERAL_MANAGER,
		OTHERS]
	}
}
